# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_providers {
        azurerm = {
          source = "hashicorp/azurerm"
          version = ">=3.10.0"
        }
        azuread = {
            source = "hashicorp/azuread"
            version = ">=2.20.0"
        }
      }
    }
    provider "azurerm" {
        features {}
        client_id            = ""
        client_secret        = ""
        tenant_id            = "93f33571-550f-43cf-b09f-cd331338d086"
        subscription_id      = "353a6255-27a8-4733-adf0-1c531ba9f4e9"
    }
    provider "azuread" {
    }
